# Loads default set of integrations. Do not remove.
default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

automation: !include automations.yaml
command_line: !include command_line.yaml
cover: !include covers.yaml
homekit: !include homekit.yaml
lovelace: !include lovelace.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
shell_command:  !include shell_command.yaml
sensor: !include sensors.yaml
template: !include_dir_merge_list templates/

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 999
  auto_purge: false
  auto_repack: true

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js

influxdb:
  host: 192.168.3.3
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_pass
  max_retries: 5
  default_measurement: state

# Text to speech
tts:
  - platform: google_translate

wake_on_lan:

panel_custom:
  - name: Supervisor
    url_path: hassio/system
    sidebar_title: Supervisor
    sidebar_icon: mdi:home-assistant
    module_url: /local/panel-redirect.js

waste_collection_schedule:
  sources:
    - name: durham_gov_uk
      args:
        uprn: "100110493335"
  day_switch_time: "12:30"
