- platform: waste_collection_schedule
  name: Rubbish Collection
  add_days_to: true
  value_template: "{{ 'on' if value.daysTo <2 else 'off' }}"
  types:
    - Rubbish bin

- platform: waste_collection_schedule
  name: Recycle Collection
  add_days_to: true
  value_template: "{{ 'on' if value.daysTo <2 else 'off' }}"
  types:
    - Recycle bin

- platform: waste_collection_schedule
  name: Garden Waste Collection
  add_days_to: true
  value_template: "{{ 'on' if value.daysTo <2 else 'off' }}"
  types:
    - Garden waste bin

- platform: systemmonitor
  resources:
    - type: disk_use_percent
    - type: disk_use
    - type: disk_free
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: processor_use
    - type: processor_temperature
    - type: last_boot